---

- block:

    - name: Download microsoft repository definition ({{ ansible_os_family }})
      get_url:
        url: https://packages.microsoft.com/config/rhel/{{ ansible_distribution_major_version }}/prod.repo
        dest: /etc/yum.repos.d/microsoft.repo
        mode: '0644'

  when: ansible_os_family == 'RedHat'

- block:

    - name: Install package with repo definition ({{ ansible_os_family }})
      apt:
        deb: https://packages.microsoft.com/config/debian/{{ ansible_distribution_major_version }}/packages-microsoft-prod.deb

    - name: Update APT cache
      apt:
        update_cache: yes
        cache_valid_time: 1

  when: ansible_distribution == 'Debian'

- block:

    - name: Install package with repo definition ({{ ansible_os_family }})
      apt:
        deb: https://packages.microsoft.com/config/ubuntu/{{ ansible_distribution_version }}/packages-microsoft-prod.deb

    - name: Update APT cache
      apt:
        update_cache: yes
        cache_valid_time: 1

  when: ansible_distribution == 'Ubuntu'

- name: Install the powershell package
  package:
    name: "{{ powershell_linux_package }}"
    state: present
  become: yes

- name: Check if the helper script directory exists
  stat:
    path: "{{ powershell_linux_script_dir }}"
  register: result
  become: yes

- name: Create helper script direcory if it does not exist
  file:
    path: "{{ powershell_linux_script_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
  when: not result.stat.exists
  become: yes

- name: Distribute all helper scripts
  copy:
    src: "{{ item }}"
    dest: "{{ powershell_linux_script_dir }}"
    mode: '0755'
  loop: "{{ powershell_linux_scripts }}"
  become: yes
