---

- name: Install powershell
  include_tasks: install-{{ powershell_install_type }}.yml

- name: Check if the helper script directory exists
  stat:
    path: "{{ powershell_linux_script_dir }}"
  register: result
  become: yes

- name: Create helper script direcory if it does not exist
  file:
    path: "{{ powershell_linux_script_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
  when: not result.stat.exists
  become: yes

- name: Distribute all helper scripts
  copy:
    src: "{{ item }}"
    dest: "{{ powershell_linux_script_dir }}"
    owner: "root"
    group: "root"
    mode: "0755"
  loop: "{{ powershell_linux_scripts }}"
  become: yes
