---

- name: Define package name to use
  set_fact:
    ps_pkg_name: "{{ ps_pkg_name }}-{{ ps_pkg_version }}"
  when: ps_pkg_version is defined

- name: Install the powershell package
  package:
    name: "{{ ps_pkg_name }}"
    state: "{{ ps_pkg_state }}"
  become: yes
  when: ps_pkg_install|bool

- name: Check if the helper script directory exists
  stat:
    path: "{{ ps_script_dir }}"
  register: result
  become: yes

- name: Create helper script direcory if it does not exist
  file:
    path: "{{ ps_script_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
  when: not result.stat.exists
  become: yes

- name: Distribute all helper scripts
  copy:
    src: "{{ item }}"
    dest: "{{ ps_script_dir }}"
    mode: '0755'
  loop: "{{ ps_scripts }}"
  become: yes
