---

- name: Install powershell
  ansible.builtin.include_tasks: install-{{ powershell_install_type }}.yml

- name: Check if the helper script directory exists
  ansible.builtin.stat:
    path: "{{ powershell_linux_script_dir }}"
  register: result
  become: yes

- name: Create helper script direcory if it does not exist
  ansible.builtin.file:
    path: "{{ powershell_linux_script_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
  when: not result.stat.exists
  become: yes

- name: Distribute all helper scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ powershell_linux_script_dir }}"
    owner: "root"
    group: "root"
    mode: "0755"
  loop: "{{ powershell_linux_scripts }}"
  become: yes
