---

- name: Install powershell
  include_tasks: install/install.yml

- name: Unregister all unwanted repositories
  include_tasks: repository/unregister.yml

- name: Register the repositories needed
  include_tasks: repository/register.yml

- name: Install all modules
  include_tasks: module/install.yml

- name: Copy powershell scripts
  copy:
    src: "{{ item }}"
    dest: "{{ powershell_linux_script_dir }}/{{ item }}"
    mode: '0755'
  loop: "{{ powershell_linux_scripts_custom }}"
