---

- name: Load variables based on OS type
  ansible.builtin.include_tasks: vars.yml

- name: Install powershell
  ansible.builtin.include_tasks: install.yml

- name: Unregister all unwanted repositories
  ansible.builtin.include_tasks: repository/unregister.yml

- name: Register the repositories needed
  ansible.builtin.include_tasks: repository/register.yml

- name: Install all modules
  ansible.builtin.include_tasks: module/install.yml

- name: Copy powershell scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ powershell_linux_script_dir }}/{{ item }}"
    mode: '0755'
  loop: "{{ powershell_linux_scripts_custom }}"
