---

- name: Load variables based on OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "family-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "family-{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - 'vars'

- name: Install powershell
  ansible.builtin.include_tasks: install.yml

- name: Unregister all unwanted repositories
  ansible.builtin.include_tasks: repository/unregister.yml

- name: Register the repositories needed
  ansible.builtin.include_tasks: repository/register.yml

- name: Install all modules
  ansible.builtin.include_tasks: module/install.yml

- name: Copy powershell scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ powershell_linux_script_dir }}/{{ item }}"
    mode: '0755'
  loop: "{{ powershell_linux_scripts_custom }}"
