---

- name: Remove all helper scripts
  ansible.builtin.file:
    path: "{{ powershell_linux_script_dir }}/{{ item }}"
    state: absent
  loop: "{{ powershell_linux_scripts }}"
  become: yes

- name: Remove package
  when: powershell_install_type == 'package'
  block:

    - name: Remove the powershell package
      ansible.builtin.package:
        name: "{{ powershell_linux_package }}"
        state: absent
      become: yes

    - name: Remove powershell repository
      ansible.builtin.yum_repository:
        name: "{{ powershell_linux_repo.name }}"
        state: absent
      become: yes

- name: Delete installation & module directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/local/share/powershell
    - /opt/microsoft/powershell
    - /root/.cache/powershell
    - /usr/bin/pwsh
  become: yes
