---
- name: Converge
  hosts: all
  vars:
    powershell_linux_repositories: []
  tasks:

    - name: "Include role 'ansible-role-powershell_linux'"
      include_role:
        name: "ansible-role-powershell_linux"
