---

- name: Converge
  hosts: all
  vars:
    powershell_linux_modules: [{'name': 'VMware.PowerCLI', 'version': '12.3.0.17860403'}]
  tasks:
    - name: Include role 'ansible-role-powershell_linux'
      include_role:
        name: ansible-role-powershell_linux
